### ISSUE TITLE
Two memory issues 

### ISSUE THREAD

**Issue by tdouilletgrellier** [szaghi/BeFoR64#11]
Hi there,

I request a little help on two issues I have when using the library.

1. On Linux, the following works :
```
real(kind=4)   :: array(3)
array = [0.0,0.0,3.0]
call b64_encode(array, code=code64)
```
but the following fails :
```
real(kind=8)   :: array(3)
array = [0.0,0.0,3.0]
call b64_encode(array,code=code64)
```
The error message is : 
`free(): invalid next size (fast): 0x00000000022799d0 ***`

2. On OSX, I sometimes have an error message saying :
`malloc: Incorrect checksum for freed object 0x7fc879e00778: probably modified after being freed.`
The moment when the program fails might slightly change but it always fails with that error.

I don't know if these two issues are connected or not. Any ideas on how to solve that ?

Thanks in advance !

Thomas

**Comment by szaghi** [comment]
Hi @tdouilletgrellier 

sorry for my delay, I am quite busy.

I have to try to replicate your test, let me some time. However, can you try a different test? I do not understand your errors (maybe a compiler issue), but your *style* is somehow lazy... for example your initialization of `array` is somehow not good for me, I prefer something along the line

```fortran
use iso_fortran_env
real(kind=real64) :: array(3)
array = [0.0_real64, 0.0_real64, 3.0_real64]
call b64_encode(array,code=code64)
```

not sure if this more compliant initialization is of any help for you, but this is a better way to deal with real precision and its conversion to base64 encoding.

I'll try your test soon.

Cheers

**Comment by tdouilletgrellier** [comment]
Hi @szaghi ,

I feel bad since I realized this morning that I did not initialized the library before in my code (It was not clear in the Wiki)

Calling b64_init before solved all my issues on both OSX and Unix.

Sorry for the inconvenience.

Best,

Thomas

PS: Yes the example I showed in my first post were lazy because I was trying to isolate the error !

**Comment by szaghi** [comment]
@tdouilletgrellier 

:-)

Do not worry, I am happy you solved the issue.

Cheers
