### ISSUE TITLE
Pure/Elemental with unlimited polymorphic

### ISSUE THREAD

**Issue by victorsndvg** [szaghi/BeFoR64#8]
Compiling Lib_VTK_IO with gcc version 5.1.0 (Ubuntu 5.1.0-0ubuntu11~14.04.1), I get the following error:

> ./src/Lib_Base64.f90:374:44:
> 
>    elemental subroutine b64_decode_up(code,up)
>                                             1
> Error: INTENT(OUT) argument 'up' of pure procedure ‘b64_decode_up’ at (1) may not be polymorphic
> ./src/Lib_Base64.f90:404:41:
> 
>    pure subroutine b64_decode_up_a(code,up)
>                                          1
> Error: INTENT(OUT) argument 'up' of pure procedure ‘b64_decode_up_a’ at (1) may not be polymorphic

It seems that returning unlimited polymorphics is not pure/elemental. You can find more info in the following link:

https://software.intel.com/en-us/forums/topic/543298

**Comment by szaghi** [comment]
Hi Victor,

thank you for raising the issue. I had just installed the gcc-5 branch on my Arch box, I will fix it soon.

See you soon,

P.S. I am reading your fork of Lib_VTK_IO for merging it into the main branch, do not lose hope!

**Comment by szaghi** [comment]
Fixed
